- hosts: localhost
  become: true
  tasks:
   - name: Log into DockerHub
     docker_login:
      username: xlshobhit
      password: Xpertladr@123
      email: joshi.shobhit@gmail.com   
      
   - name: Pull image from docker hub
     command: docker pull xlshobhit/devopsdemo:"{{buildNumber}}"

   - name: Stop current running container
     command: docker stop shobhit-c1
     ignore_errors: yes

   - name: Remove stopped container
     command: docker rm shobhit-c1
     ignore_errors: yes

   - name: Run a container from the pulled image
     command: docker run -d --name shobhit-c1 -p 9500:80 xlshobhit/devopsdemo:"{{buildNumber}}"